import { ReactNode } from 'react';

import type { Metadata } from 'next';

import RootHead from '@/client/ui/helpers/head';

import '@/utils/styles/global.scss';
import '@/utils/styles/normalize.css';
import '@/utils/styles/tokens/light/lightTheme.scss';

import { fonts } from './fonts';
import { Providers } from './providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="ru" className={fonts.rubik.variable}>
			<RootHead />
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
